# Find more information on toml format here:?  https://github.com/toml-lang/toml???
modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
modId="the_bumblezone" #mandatory
logoFile=""
version="${version}" #mandatory
displayName="The Bumblezone" #mandatory
displayURL="..."
authors="TelepathicGrunt"
credits="Thanks to Commoble for suggesting this awesome name for this mod! Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
# The description text for the mod (multi line!) (#mandatory)
description='''BEEEEEEEEEEEEEEES!!!'''