modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
modId="the_bumblezone" #mandatory
logoFile="the_bumblezone_logo.png"
version="${version}" #mandatory
displayName="The Bumblezone" #mandatory
displayURL="..."
authors="TelepathicGrunt"
credits="Thanks to Commoble for suggesting this awesome name for this mod! Special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
description='''An awesome dimension full of bees that becomes REALLY angry if you take their honey! Enter the dimension by throwing an enderpearl at Bee Nest and exit it by going above Y = 256 to below Y = 0.'''