modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory 
issueTrackerURL="https://github.com/TelepathicGrunt/RepurposedStructures/issues" #optional
license="https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.16/LICENSE"

[[mods]] #mandatory
modId="repurposed_structures" #mandatory
logoFile="RepurposedStructuresLogo.png"
version="${version}" #mandatory
displayName="Repurposed Structures" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/repurposed-structures"
authors="TelepathicGrunt"
description='''
Taking existing vanilla structures and changing them up for extra variety!
'''